language: python

# See https://github.com/travis-ci/travis-ci/issues/9815#issuecomment-401756442
sudo: true
dist: xenial

branches:
  - master

python:
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"

install:
  - pip install black flake8 pytest praw

script:
  # See https://github.com/PyCQA/pycodestyle/issues/728
  - flake8 --ignore=E501,W503,E722 --statistics
  - black --check --verbose .
# - py.test --verbose -k "not TestFindURLsFunction" --showlocals --full-trace --junit-xml=/dev/null .

env:
matrix:
  allow_failures:
    - python: "3.6"
    - python: "3.6-dev"
    - python: "3.7-dev"

  fast_finish: true

cache: pip